#!/bin/bash

echo "🚀 배포 준비 완료!"
echo ""
echo "다음 단계를 따라주세요:"
echo ""
echo "1️⃣  GitHub에서 새 저장소 생성"
echo "   - https://github.com/new 접속"
echo "   - 저장소 이름 입력 (예: song-mi-jung-website)"
echo "   - Public 또는 Private 선택"
echo "   - 'Initialize this repository with a README' 체크 해제"
echo "   - 'Create repository' 클릭"
echo ""
echo "2️⃣  아래 명령어 실행 (저장소 URL을 복사해서 사용):"
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣  Vercel 배포"
echo "   - https://vercel.com 접속"
echo "   - GitHub 계정으로 로그인"
echo "   - 'New Project' 클릭"
echo "   - 방금 만든 저장소 선택"
echo "   - Root Directory: apps/song-mi-jung-website"
echo "   - 'Deploy' 클릭"
echo ""
echo "✅ 완료! 실제 주소로 배포됩니다!"
